/**
 * Bundled skill i18n key maps — mirrors the tool-group-defs.ts pattern.
 * skillKey (from SKILL.md `name`) → i18n label/description key.
 * Keys not present here fall through and render server-supplied strings.
 */

export const SKILL_LABEL_KEY: Record<string, string> = {
  "coding-agent":           "tenantSkills.skillLabelCodingAgent",
  "healthcheck":            "tenantSkills.skillLabelHealthcheck",
  "mcporter":               "tenantSkills.skillLabelMcporter",
  "memory-manager":         "tenantSkills.skillLabelMemoryManager",
  "pingtest":               "tenantSkills.skillLabelPingtest",
  "session-logs":           "tenantSkills.skillLabelSessionLogs",
  "skill-creator":          "tenantSkills.skillLabelSkillCreator",
  "weather":                "tenantSkills.skillLabelWeather",
  "feishu-ask-user":        "tenantSkills.skillLabelFeishuAskUser",
  "feishu-auth":            "tenantSkills.skillLabelFeishuAuth",
  "feishu-bitable":         "tenantSkills.skillLabelFeishuBitable",
  "feishu-calendar":        "tenantSkills.skillLabelFeishuCalendar",
  "feishu-chat":            "tenantSkills.skillLabelFeishuChat",
  "feishu-create-doc":      "tenantSkills.skillLabelFeishuCreateDoc",
  "feishu-doc-comment":     "tenantSkills.skillLabelFeishuDocComment",
  "feishu-doc-media":       "tenantSkills.skillLabelFeishuDocMedia",
  "feishu-docx-download":   "tenantSkills.skillLabelFeishuDocxDownload",
  "feishu-drive":           "tenantSkills.skillLabelFeishuDrive",
  "feishu-fetch-doc":       "tenantSkills.skillLabelFeishuFetchDoc",
  "feishu-im-file-analyze": "tenantSkills.skillLabelFeishuImFileAnalyze",
  "feishu-im-message":      "tenantSkills.skillLabelFeishuImMessage",
  "feishu-im-read":         "tenantSkills.skillLabelFeishuImRead",
  "feishu-image-ocr":       "tenantSkills.skillLabelFeishuImageOcr",
  "feishu-meeting-minutes": "tenantSkills.skillLabelFeishuMeetingMinutes",
  "feishu-quick-setup":     "tenantSkills.skillLabelFeishuQuickSetup",
  "feishu-search-doc":      "tenantSkills.skillLabelFeishuSearchDoc",
  "feishu-search-user":     "tenantSkills.skillLabelFeishuSearchUser",
  "feishu-sheet":           "tenantSkills.skillLabelFeishuSheet",
  "feishu-task":            "tenantSkills.skillLabelFeishuTask",
  "feishu-update-doc":      "tenantSkills.skillLabelFeishuUpdateDoc",
  "feishu-wiki":            "tenantSkills.skillLabelFeishuWiki",
};

export const SKILL_DESC_KEY: Record<string, string> = {
  "coding-agent":           "tenantSkills.skillCodingAgent",
  "healthcheck":            "tenantSkills.skillHealthcheck",
  "mcporter":               "tenantSkills.skillMcporter",
  "memory-manager":         "tenantSkills.skillMemoryManager",
  "pingtest":               "tenantSkills.skillPingtest",
  "session-logs":           "tenantSkills.skillSessionLogs",
  "skill-creator":          "tenantSkills.skillSkillCreator",
  "weather":                "tenantSkills.skillWeather",
  "feishu-ask-user":        "tenantSkills.skillFeishuAskUser",
  "feishu-auth":            "tenantSkills.skillFeishuAuth",
  "feishu-bitable":         "tenantSkills.skillFeishuBitable",
  "feishu-calendar":        "tenantSkills.skillFeishuCalendar",
  "feishu-chat":            "tenantSkills.skillFeishuChat",
  "feishu-create-doc":      "tenantSkills.skillFeishuCreateDoc",
  "feishu-doc-comment":     "tenantSkills.skillFeishuDocComment",
  "feishu-doc-media":       "tenantSkills.skillFeishuDocMedia",
  "feishu-docx-download":   "tenantSkills.skillFeishuDocxDownload",
  "feishu-drive":           "tenantSkills.skillFeishuDrive",
  "feishu-fetch-doc":       "tenantSkills.skillFeishuFetchDoc",
  "feishu-im-file-analyze": "tenantSkills.skillFeishuImFileAnalyze",
  "feishu-im-message":      "tenantSkills.skillFeishuImMessage",
  "feishu-im-read":         "tenantSkills.skillFeishuImRead",
  "feishu-image-ocr":       "tenantSkills.skillFeishuImageOcr",
  "feishu-meeting-minutes": "tenantSkills.skillFeishuMeetingMinutes",
  "feishu-quick-setup":     "tenantSkills.skillFeishuQuickSetup",
  "feishu-search-doc":      "tenantSkills.skillFeishuSearchDoc",
  "feishu-search-user":     "tenantSkills.skillFeishuSearchUser",
  "feishu-sheet":           "tenantSkills.skillFeishuSheet",
  "feishu-task":            "tenantSkills.skillFeishuTask",
  "feishu-update-doc":      "tenantSkills.skillFeishuUpdateDoc",
  "feishu-wiki":            "tenantSkills.skillFeishuWiki",
};
