import { randomUUID } from "node:crypto";
import type { IncomingMessage, ServerResponse } from "node:http";
import { createInteractionTrace } from "../db/models/interaction-trace.js";
import { getTenantAgent } from "../db/models/tenant-agent.js";
import { listTenantModels } from "../db/models/tenant-model.js";
import { isModelTier, type ModelTier } from "../db/types.js";
import { createSubsystemLogger } from "../logging/subsystem.js";
import { resolveGatewayToken } from "./gateway-token-cache.js";
import { readJsonBody } from "./hooks.js";
import { sendJson, sendMethodNotAllowed } from "./http-common.js";
import { getHeader } from "./http-utils.js";
import { resolveTierChain, TierChainError, isRetriableFailover } from "./tier-chain.js";

const log = createSubsystemLogger("agent-chat-api");

const MAX_BODY_BYTES = 1024 * 1024;

type ChatMessage = { role: string; content: string };

function sendError(
  res: ServerResponse,
  status: number,
  message: string,
  type = "invalid_request_error",
) {
  sendJson(res, status, { error: { message, type } });
}

/**
 * POST /v1/agent/chat/completions — lightweight LLM proxy for tenant agents.
 *
 * Auth: Authorization: Bearer <ENCLAWS_GATEWAY_TOKEN>, where the token is an
 * opaque reference (generated by EC during exec tool invocation) to a cached
 * sessionKey entry. Gateway resolves the token to attribution info (tenantId /
 * agentSlug / channel / userIds / sessionLabel) and routes accordingly.
 *
 * Body: { messages: [...], model_tier?: "lite"|"standard"|"pro" }
 * - model_tier is reserved for future three-tier model routing; v1 logs it
 *   and still uses the agent's default model.
 */
export async function handleAgentChatHttpRequest(
  req: IncomingMessage,
  res: ServerResponse,
): Promise<boolean> {
  const pathname = new URL(req.url ?? "/", "http://localhost").pathname;
  if (pathname !== "/v1/agent/chat/completions") {
    return false;
  }

  if (req.method !== "POST") {
    sendMethodNotAllowed(res);
    return true;
  }

  // --- 1. Extract Authorization: Bearer <token> ---
  const authHeader = getHeader(req, "authorization")?.trim();
  const token = authHeader?.replace(/^Bearer\s+/i, "").trim();
  if (!token) {
    sendError(res, 401, "Missing Authorization: Bearer <token>", "unauthorized");
    return true;
  }

  // --- 2. Resolve token to sessionKey entry ---
  const tokenEntry = resolveGatewayToken(token);
  if (!tokenEntry) {
    sendError(res, 401, "Invalid or expired token", "unauthorized");
    return true;
  }

  // --- 3. Redundant tenant header validation ---
  const headerTenantId = getHeader(req, "x-enclaws-tenant-id")?.trim();
  if (!headerTenantId) {
    sendError(res, 400, "Missing required header: x-enclaws-tenant-id");
    return true;
  }
  if (headerTenantId !== tokenEntry.tenantId) {
    sendError(res, 403, "Tenant mismatch between token and header", "forbidden");
    return true;
  }

  const tenantId = tokenEntry.tenantId;
  const agentId = tokenEntry.agentSlug;
  const channel = tokenEntry.channel;
  const userUnionId = tokenEntry.userUnionId;

  // --- 4. Parse body ---
  const bodyResult = await readJsonBody(req, MAX_BODY_BYTES);
  if (!bodyResult.ok) {
    sendError(res, 400, `Invalid request body: ${bodyResult.error}`);
    return true;
  }
  const body = bodyResult.value as Record<string, unknown>;
  const messages = body.messages as ChatMessage[] | undefined;
  if (!Array.isArray(messages) || messages.length === 0) {
    sendError(res, 400, "Missing or empty `messages` array");
    return true;
  }

  // --- 5. Validate model_tier (optional) ---
  const modelTierRaw = body.model_tier;
  let modelTier: string | undefined;
  if (modelTierRaw !== undefined && modelTierRaw !== null) {
    if (!isModelTier(modelTierRaw)) {
      sendError(res, 400, "model_tier must be one of: lite, standard, pro");
      return true;
    }
    modelTier = modelTierRaw;
  }

  log.info(
    `model_tier=${modelTier ?? "(not provided)"} tenant=${tenantId} agent=${agentId} token=${token.slice(0, 12)}...`,
  );

  // --- 6. Load agent (scoped by tenantId + agentSlug) ---
  let agent;
  try {
    agent = await getTenantAgent(tenantId, agentId);
  } catch (err) {
    log.error(`Failed to query tenant_agents: ${String(err)}`);
    sendError(res, 500, "Internal error querying agent config", "api_error");
    return true;
  }
  if (!agent) {
    sendError(res, 404, `Agent not found: tenantId=${tenantId} agentId=${agentId}`, "not_found");
    return true;
  }

  // --- 7. Resolve tier chain (v4: tier-aware model routing) ---
  let tenantModels;
  try {
    tenantModels = await listTenantModels(tenantId);
  } catch (err) {
    log.error(`Failed to list tenant_models: ${String(err)}`);
    sendError(res, 500, "Internal error querying model config", "api_error");
    return true;
  }

  // Agent's preferred default tier for cross-tier fallback when the caller
  // didn't pin a tier. Stored in agent.config by the tenant-agents UI.
  const rawAgentDefaultTier = (agent.config as Record<string, unknown> | undefined)?.defaultTier;
  const agentDefaultTier = isModelTier(rawAgentDefaultTier) ? rawAgentDefaultTier : undefined;

  let chain;
  try {
    chain = resolveTierChain(
      agent.modelConfig ?? [],
      tenantModels,
      modelTier as ModelTier | undefined,
      agentDefaultTier,
    );
  } catch (err) {
    if (err instanceof TierChainError) {
      const status = err.code === "TIER_NOT_CONFIGURED" ? 400 : 404;
      sendError(res, status, err.message, err.code.toLowerCase());
      return true;
    }
    throw err;
  }

  // --- 8. Turn ID (per-request; no header anymore) ---
  const turnId = randomUUID();
  const turnIndex = 0;
  const runId = `agentchat_${randomUUID()}`;

  // Map each chain entry to its tier so the failover log can point at
  // 'TIER_FALLBACK: pro → standard' whenever the loop crosses tiers.
  // Legacy models (tier undefined) are reported as 'standard' — matches
  // the runtime fallback in resolveTierChain.
  const entryTier = (entry: { providerId: string; modelId: string }): ModelTier => {
    const p = tenantModels.find((m) => m.id === entry.providerId);
    const def = p?.models.find((m) => m.id === entry.modelId);
    return (def?.tier ?? "standard") as ModelTier;
  };

  log.info(
    `tier-chain resolved turn=${turnId} requested=${modelTier ?? "(none)"} agentDefault=${agentDefaultTier ?? "(none)"} chain=[${chain
      .map((e, i) => `#${i + 1}:${entryTier(e)}/${e.modelId}`)
      .join(", ")}]`,
  );

  // --- 9. Failover loop: try each entry in chain, skip retriable failures ---
  let lastError: unknown = null;
  let prevTier: ModelTier | undefined;

  for (const [idx, chainEntry] of chain.entries()) {
    const currentTier = entryTier(chainEntry);
    // Crossed a tier boundary — the prior tier is exhausted. Log at warn
    // so this shows up in default log filtering (info is often dropped).
    if (prevTier !== undefined && prevTier !== currentTier) {
      log.warn(
        `TIER_FALLBACK turn=${turnId} ${prevTier} → ${currentTier} (prior tier exhausted after ${idx} attempt${idx === 1 ? "" : "s"})`,
      );
    }
    prevTier = currentTier;
    const tenantModel = tenantModels.find((m) => m.id === chainEntry.providerId);
    if (!tenantModel) {
      lastError = new Error(`Model provider not found: providerId=${chainEntry.providerId}`);
      log.warn(
        `tier-chain attempt[${idx + 1}/${chain.length}] skip turn=${turnId} tier=${currentTier} model=${chainEntry.modelId} reason=provider_not_found`,
      );
      continue;
    }

    const baseUrl = tenantModel.baseUrl?.replace(/\/+$/, "") ?? "";
    const apiKey = tenantModel.apiKeyEncrypted ?? "";
    const modelId = chainEntry.modelId;

    if (!baseUrl) {
      lastError = new Error(`Model provider has no baseUrl: providerId=${chainEntry.providerId}`);
      log.warn(
        `tier-chain attempt[${idx + 1}/${chain.length}] skip turn=${turnId} tier=${currentTier} model=${modelId} reason=no_baseurl`,
      );
      continue;
    }

    log.info(
      `tier-chain attempt[${idx + 1}/${chain.length}] turn=${turnId} tier=${currentTier} provider=${tenantModel.providerType} model=${modelId}`,
    );

    const startedAt = Date.now();
    try {
      const llmUrl = `${baseUrl}/chat/completions`;
      const headers: Record<string, string> = { "Content-Type": "application/json" };
      if (apiKey) headers["Authorization"] = `Bearer ${apiKey}`;
      if (tenantModel.extraHeaders) Object.assign(headers, tenantModel.extraHeaders);

      const fetchResponse = await fetch(llmUrl, {
        method: "POST",
        headers,
        body: JSON.stringify({ model: modelId, messages, stream: false }),
      });

      if (!fetchResponse.ok) {
        const errorText = await fetchResponse.text().catch(() => "unknown error");
        const httpErr = new Error(
          `LLM request failed: status=${fetchResponse.status} body=${errorText.slice(0, 500)}`,
        );
        (httpErr as Error & { status?: number }).status = fetchResponse.status;
        throw httpErr;
      }

      const llmResponse = (await fetchResponse.json()) as Record<string, unknown>;
      const durationMs = Date.now() - startedAt;

      // Success — extract usage, record trace, send response
      const usage = llmResponse.usage as Record<string, number> | undefined;
      const choices = llmResponse.choices as Array<Record<string, unknown>> | undefined;
      const assistantContent = (choices?.[0]?.message as Record<string, unknown>)?.content as
        | string
        | undefined;
      const stopReason = (choices?.[0]?.finish_reason as string) ?? undefined;

      void createInteractionTrace({
        tenantId,
        userId: userUnionId,
        sessionKey: tokenEntry.internalSessionKey,
        agentId,
        channel,
        turnId,
        turnIndex,
        userInput: messages.find((m) => m.role === "user")?.content,
        provider: tenantModel.providerType,
        model: modelId,
        messages,
        response: assistantContent ? [{ type: "text", text: assistantContent }] : null,
        stopReason,
        inputTokens: usage?.prompt_tokens ?? 0,
        outputTokens: usage?.completion_tokens ?? 0,
        durationMs,
      }).catch((traceErr) => log.warn(`Failed to record trace: ${String(traceErr)}`));

      log.info(
        `tier-chain success turn=${turnId} winner=${currentTier}/${modelId} provider=${tenantModel.providerType} attempt=${idx + 1}/${chain.length} durationMs=${durationMs}`,
      );

      sendJson(res, 200, {
        id: runId,
        object: "chat.completion",
        created: Math.floor(Date.now() / 1000),
        model: modelId,
        choices: [
          {
            index: 0,
            message: { role: "assistant", content: assistantContent ?? "" },
            finish_reason: stopReason ?? "stop",
          },
        ],
        usage: {
          prompt_tokens: usage?.prompt_tokens ?? 0,
          completion_tokens: usage?.completion_tokens ?? 0,
          total_tokens: usage?.total_tokens ?? 0,
        },
      });

      return true;
    } catch (err) {
      lastError = err;
      const durationMs = Date.now() - startedAt;

      // Always record the failed attempt so admins see the failover chain
      void createInteractionTrace({
        tenantId,
        userId: userUnionId,
        sessionKey: tokenEntry.internalSessionKey,
        agentId,
        channel,
        turnId,
        turnIndex,
        userInput: messages.find((m) => m.role === "user")?.content,
        provider: tenantModel.providerType,
        model: modelId,
        messages,
        errorMessage: String(err).slice(0, 500),
        durationMs,
      }).catch((traceErr) => log.warn(`Failed to record error trace: ${String(traceErr)}`));

      const { retriable, status } = isRetriableFailover(err);
      if (retriable) {
        log.warn(
          `tier-chain attempt[${idx + 1}/${chain.length}] failed turn=${turnId} tier=${currentTier} model=${modelId} status=${status ?? "n/a"} — will fall through to next entry; err=${String(err).slice(0, 200)}`,
        );
      } else {
        log.error(
          `tier-chain attempt[${idx + 1}/${chain.length}] failed turn=${turnId} tier=${currentTier} model=${modelId} status=${status ?? "n/a"} non-retriable — bailing chain; err=${String(err).slice(0, 200)}`,
        );
        // Non-retriable (4xx non-429, auth, billing, content-policy) —
        // surface to caller immediately; don't burn the rest of the chain.
        sendError(res, status ?? 502, `LLM request failed: ${String(err).slice(0, 500)}`, "api_error");
        return true;
      }
      // Retriable — fall through to next entry in chain
    }
  }

  // --- 10. Chain exhausted — all entries failed with retriable errors ---
  log.error(
    `TIER_EXHAUSTED turn=${turnId} all ${chain.length} entries failed; last=${String(lastError).slice(0, 200)}`,
  );
  sendError(
    res,
    503,
    `TIER_EXHAUSTED: all models in tier failed (last: ${String(lastError).slice(0, 500)})`,
    "tier_exhausted",
  );
  return true;
}
