import { randomUUID } from "node:crypto";
import type { IncomingMessage, ServerResponse } from "node:http";
import { createInteractionTrace } from "../db/models/interaction-trace.js";
import { getTenantAgent } from "../db/models/tenant-agent.js";
import { getTenantModel } from "../db/models/tenant-model.js";
import { createSubsystemLogger } from "../logging/subsystem.js";
import { resolveGatewayToken } from "./gateway-token-cache.js";
import { readJsonBody } from "./hooks.js";
import { sendJson, sendMethodNotAllowed } from "./http-common.js";
import { getHeader } from "./http-utils.js";

const log = createSubsystemLogger("agent-chat-api");

const MAX_BODY_BYTES = 1024 * 1024;
const MODEL_TIER_VALUES = new Set(["lite", "standard", "pro"]);

type ChatMessage = { role: string; content: string };

function sendError(
  res: ServerResponse,
  status: number,
  message: string,
  type = "invalid_request_error",
) {
  sendJson(res, status, { error: { message, type } });
}

/**
 * POST /v1/agent/chat/completions — lightweight LLM proxy for tenant agents.
 *
 * Auth: Authorization: Bearer <ENCLAWS_GATEWAY_TOKEN>, where the token is an
 * opaque reference (generated by EC during exec tool invocation) to a cached
 * sessionKey entry. Gateway resolves the token to attribution info (tenantId /
 * agentSlug / channel / userIds / sessionLabel) and routes accordingly.
 *
 * Body: { messages: [...], model_tier?: "lite"|"standard"|"pro" }
 * - model_tier is reserved for future three-tier model routing; v1 logs it
 *   and still uses the agent's default model.
 */
export async function handleAgentChatHttpRequest(
  req: IncomingMessage,
  res: ServerResponse,
): Promise<boolean> {
  const pathname = new URL(req.url ?? "/", "http://localhost").pathname;
  if (pathname !== "/v1/agent/chat/completions") {
    return false;
  }

  if (req.method !== "POST") {
    sendMethodNotAllowed(res);
    return true;
  }

  // --- 1. Extract Authorization: Bearer <token> ---
  const authHeader = getHeader(req, "authorization")?.trim();
  const token = authHeader?.replace(/^Bearer\s+/i, "").trim();
  if (!token) {
    sendError(res, 401, "Missing Authorization: Bearer <token>", "unauthorized");
    return true;
  }

  // --- 2. Resolve token to sessionKey entry ---
  const entry = resolveGatewayToken(token);
  if (!entry) {
    sendError(res, 401, "Invalid or expired token", "unauthorized");
    return true;
  }

  // --- 3. Redundant tenant header validation ---
  const headerTenantId = getHeader(req, "x-enclaws-tenant-id")?.trim();
  if (!headerTenantId) {
    sendError(res, 400, "Missing required header: x-enclaws-tenant-id");
    return true;
  }
  if (headerTenantId !== entry.tenantId) {
    sendError(res, 403, "Tenant mismatch between token and header", "forbidden");
    return true;
  }

  const tenantId = entry.tenantId;
  const agentId = entry.agentSlug;
  const channel = entry.channel;
  const userUnionId = entry.userUnionId;

  // --- 4. Parse body ---
  const bodyResult = await readJsonBody(req, MAX_BODY_BYTES);
  if (!bodyResult.ok) {
    sendError(res, 400, `Invalid request body: ${bodyResult.error}`);
    return true;
  }
  const body = bodyResult.value as Record<string, unknown>;
  const messages = body.messages as ChatMessage[] | undefined;
  if (!Array.isArray(messages) || messages.length === 0) {
    sendError(res, 400, "Missing or empty `messages` array");
    return true;
  }

  // --- 5. Validate model_tier (optional) ---
  const modelTierRaw = body.model_tier;
  let modelTier: string | undefined;
  if (modelTierRaw !== undefined && modelTierRaw !== null) {
    if (typeof modelTierRaw !== "string" || !MODEL_TIER_VALUES.has(modelTierRaw)) {
      sendError(res, 400, "model_tier must be one of: lite, standard, pro");
      return true;
    }
    modelTier = modelTierRaw;
  }

  log.info(
    `model_tier=${modelTier ?? "(not provided)"} tenant=${tenantId} agent=${agentId} token=${token.slice(0, 12)}...`,
  );

  // --- 6. Load agent (scoped by tenantId + agentSlug) ---
  let agent;
  try {
    agent = await getTenantAgent(tenantId, agentId);
  } catch (err) {
    log.error(`Failed to query tenant_agents: ${String(err)}`);
    sendError(res, 500, "Internal error querying agent config", "api_error");
    return true;
  }
  if (!agent) {
    sendError(res, 404, `Agent not found: tenantId=${tenantId} agentId=${agentId}`, "not_found");
    return true;
  }

  // --- 7. Resolve default model (v1: ignore model_tier, use agent default) ---
  const defaultModelEntry = agent.modelConfig?.find((m) => m.isDefault);
  if (!defaultModelEntry) {
    sendError(res, 404, "No default model configured for this agent", "not_found");
    return true;
  }

  // --- 8. Load tenant model ---
  let tenantModel;
  try {
    tenantModel = await getTenantModel(tenantId, defaultModelEntry.providerId);
  } catch (err) {
    log.error(`Failed to query tenant_models: ${String(err)}`);
    sendError(res, 500, "Internal error querying model config", "api_error");
    return true;
  }
  if (!tenantModel) {
    sendError(
      res,
      404,
      `Model provider not found: providerId=${defaultModelEntry.providerId}`,
      "not_found",
    );
    return true;
  }

  const baseUrl = tenantModel.baseUrl?.replace(/\/+$/, "") ?? "";
  const apiKey = tenantModel.apiKeyEncrypted ?? "";
  const modelId = defaultModelEntry.modelId;

  if (!baseUrl) {
    sendError(res, 404, "Model provider has no baseUrl configured", "not_found");
    return true;
  }

  // --- 9. turnId (no header anymore; always fresh) ---
  const turnId = randomUUID();
  const turnIndex = 0;

  // --- 10. Call LLM ---
  const runId = `agentchat_${randomUUID()}`;
  const startedAt = Date.now();
  let llmResponse: Record<string, unknown>;

  try {
    const llmUrl = `${baseUrl}/chat/completions`;
    const headers: Record<string, string> = {
      "Content-Type": "application/json",
    };
    if (apiKey) {
      headers["Authorization"] = `Bearer ${apiKey}`;
    }
    if (tenantModel.extraHeaders) {
      Object.assign(headers, tenantModel.extraHeaders);
    }

    const fetchResponse = await fetch(llmUrl, {
      method: "POST",
      headers,
      body: JSON.stringify({
        model: modelId,
        messages,
        stream: false,
      }),
    });

    if (!fetchResponse.ok) {
      const errorText = await fetchResponse.text().catch(() => "unknown error");
      log.error(`LLM request failed: status=${fetchResponse.status} body=${errorText}`);
      sendError(res, 502, `LLM request failed: ${fetchResponse.status}`, "api_error");

      const durationMs = Date.now() - startedAt;
      void createInteractionTrace({
        tenantId,
        userId: userUnionId,
        sessionKey: entry.internalSessionKey,
        agentId,
        channel,
        turnId,
        turnIndex,
        userInput: messages.find((m) => m.role === "user")?.content,
        provider: tenantModel.providerType,
        model: modelId,
        messages,
        errorMessage: `${fetchResponse.status}: ${errorText.slice(0, 500)}`,
        durationMs,
      }).catch((traceErr) => log.warn(`Failed to record error trace: ${String(traceErr)}`));

      return true;
    }

    llmResponse = (await fetchResponse.json()) as Record<string, unknown>;
  } catch (err) {
    const durationMs = Date.now() - startedAt;
    log.error(`LLM request error: ${String(err)}`);
    sendError(res, 502, `LLM request failed: ${String(err)}`, "api_error");

    void createInteractionTrace({
      tenantId,
      userId: userUnionId,
      sessionKey: entry.internalSessionKey,
      agentId,
      channel,
      turnId,
      turnIndex,
      userInput: messages.find((m) => m.role === "user")?.content,
      provider: tenantModel.providerType,
      model: modelId,
      messages,
      errorMessage: String(err).slice(0, 500),
      durationMs,
    }).catch((traceErr) => log.warn(`Failed to record error trace: ${String(traceErr)}`));

    return true;
  }

  const durationMs = Date.now() - startedAt;

  // --- 11. Extract usage and record trace ---
  const usage = llmResponse.usage as Record<string, number> | undefined;
  const choices = llmResponse.choices as Array<Record<string, unknown>> | undefined;
  const assistantContent = (choices?.[0]?.message as Record<string, unknown>)?.content as
    | string
    | undefined;
  const stopReason = (choices?.[0]?.finish_reason as string) ?? undefined;

  void createInteractionTrace({
    tenantId,
    userId: userUnionId,
    sessionKey: entry.internalSessionKey,
    agentId,
    channel,
    turnId,
    turnIndex,
    userInput: messages.find((m) => m.role === "user")?.content,
    provider: tenantModel.providerType,
    model: modelId,
    messages,
    response: assistantContent ? [{ type: "text", text: assistantContent }] : null,
    stopReason,
    inputTokens: usage?.prompt_tokens ?? 0,
    outputTokens: usage?.completion_tokens ?? 0,
    durationMs,
  }).catch((traceErr) => log.warn(`Failed to record trace: ${String(traceErr)}`));

  // --- 12. Return response ---
  sendJson(res, 200, {
    id: runId,
    object: "chat.completion",
    created: Math.floor(Date.now() / 1000),
    model: modelId,
    choices: [
      {
        index: 0,
        message: { role: "assistant", content: assistantContent ?? "" },
        finish_reason: stopReason ?? "stop",
      },
    ],
    usage: {
      prompt_tokens: usage?.prompt_tokens ?? 0,
      completion_tokens: usage?.completion_tokens ?? 0,
      total_tokens: usage?.total_tokens ?? 0,
    },
  });

  return true;
}
